#ifndef SIMDJSON_CONDITIONAL_INCLUDE
#include "simdjson/stdsimd/base.h"
#endif // SIMDJSON_CONDITIONAL_INCLUDE

#if !SIMDJSON_CAN_ALWAYS_RUN_STDSIMD
SIMDJSON_UNTARGET_REGION
#endif

#undef SIMDJSON_IMPLEMENTATION
