#ifndef SIMDJSON_CONDITIONAL_INCLUDE
#include "simdjson/sve/base.h"
#endif // SIMDJSON_CONDITIONAL_INCLUDE

#if !SIMDJSON_CAN_ALWAYS_RUN_SVE
SIMDJSON_UNTARGET_REGION
#endif

#undef SIMDJSON_IMPLEMENTATION
